### ISSUE TITLE
Change the font in header section

### ISSUE THREAD

**Issue by rahulrachh** [ashutosh1919/masterPortfolio#104]
I would like to change the font with which my name appears in the top right corner in the header section. I searched in the project but couldn't find it. Please can anybody help me here. Saw that [@th3c0d3br34ker](https://th3c0d3br34ker.github.io/) has changed the font and would like to do that.

**Comment by ashutosh1919** [comment]
The font of the header logo is Agustina Regular it is imported in `index.css`. you can import your own font there and you can use it wherever you want.

**Comment by rahulrachh** [comment]
Thanks, Ashutosh.
