### ISSUE TITLE
Dividing "Contact Page" into segments smiliar to Experience Page

### ISSUE THREAD

**Issue by Param-29** [ashutosh1919/masterPortfolio#107]
The contact page is pretty rigid and we cannot remove parts of the contact page. 
Example: 
Blogging: For someone like me, I am not much into blogging and hence don't want to add that section. But the current version doesn't allow me to remove a section from the contacts page. 

Btw great website and design. 

PS: Sorry I am not a web developer so cannot take up the issue. Please feel free to work on this issue.

**Comment by dhruvkrishnavaid** [comment]
A quick fix for your problem is to remove the line no. 7 (that BlogsImg import), and line no. 58 to 87 (totally remove the 2nd Fade component). 😅😆

**Comment by saiteja13427** [comment]
@dhruvkrishnavaid answer solves this issue.

I have noted down this point and we will discuss and work on adding an object to the portfolio.js file wherein we can have various components and giving false to a component will remove the component from the website.

This will probably add to the customizability. 

Closing this issue for now. 

@Param-29 feel free to raise an issue in case you still have a problem.
