### ISSUE TITLE
How to set Experience card as expanded by default?

### ISSUE THREAD

**Issue by ifsheldon** [ashutosh1919/masterPortfolio#121]
Hi! I like this repo very much and thank you all.
One question I have is how I can set the cards in Experience expanded as a default. I am completely new to React, but I have searched a bit. It seems cards are wrapped in`Panel`s that are wrapped in an `Accordion`. For instance, in your live example, what can I do such that the work experiences are expanded by default?

So, it seems I should change some properties of the `Panel`s, right? But I cannot find a field like `expanded = ture` etc when I googled the API of `Panel`.

Can you please tell me how to do that? Thank you!

**Comment by ashutosh1919** [comment]
@ifsheldon , the Accordian is taken from [baseweb](https://baseweb.design/components/accordion/) by uber. you can check their website for more features. feel free to contribute here as well by raising PR

**Comment by ifsheldon** [comment]
yeah...... I actually found the link you mentioned before writing this issue, but not found anything useful to address this problem

**Comment by Walf-dev** [comment]
I resolved it by adding expanded ={true} to the Panel tag  `<Panel expanded={true}></Panel>`

**Comment by ashutosh1919** [comment]
Closing this since reply by @Walf-dev resolves the issue.
