### ISSUE TITLE
How to generate different sizes of icons fast?

### ISSUE THREAD

**Issue by ifsheldon** [ashutosh1919/masterPortfolio#123]
I see in `public/`, there are many icons and pictures of different sizes, but how can I generate these quickly? Is there any tools  doing this? Like, I give it a picture and it will generate downsized icons for me

**Comment by ashutosh1919** [comment]
@ifsheldon there are many online websites available to do so. We have also extracted favicon from one of those websites.

**Comment by jatinS-dev** [comment]
https://www.favicon-generator.org/  use this website to generate Fav Icons

**Comment by saiteja13427** [comment]
I assume this issue is now solved.

Thus closing this issue!
