### ISSUE TITLE
There is a horizontal scroll in "open-source" page in mobile view. Its due to the PullRequest and IssueRequest pie chart CSS. Fix it!

### ISSUE THREAD

**Issue by vanoop729** [ashutosh1919/masterPortfolio#124]
Look into the CSS part of IssueRequest and PullRequest

**Comment by vanoop729** [comment]
Can I open a Pull Request for the same, @ashutosh1919 ?

**Comment by ashutosh1919** [comment]
@vanoop729 , If you want to contribute, Please feel free to raise PR

**Comment by vanoop729** [comment]
Will do!

**Comment by vanoop729** [comment]
This is how I customized it: [https://anoopv.me/](https://anoopv.me/)

**Comment by saiteja13427** [comment]
Reviewed and merged the respective PR!

Thanks, @vanoop729 

The issue is now solved.

Thus closing this issue!
