### ISSUE TITLE
Centre Text `h1` tags under 'What I Do?' section ( Image Attached )

### ISSUE THREAD

**Issue by AnirudhPanda** [ashutosh1919/masterPortfolio#133]
![Capture](https://user-images.githubusercontent.com/66218496/125967493-5d1b1f07-42d9-4a3b-adb4-079421440e0b.PNG)

I can work on this!

**Comment by ashutosh1919** [comment]
IMO, there is a reason why I didn't center it. Both elements (Header and icons) looks disconnected if not aligned. If you really want to contribute on something, I would really suggest you to improve mobile responsiveness of CSS is the one that you can contribute. Some of the components break on mobile screens.

**Comment by AnirudhPanda** [comment]
> IMO, there is a reason why I didn't center it. Both elements (Header and icons) looks disconnected if not aligned. If you really want to contribute on something, I would really suggest you to improve mobile responsiveness of CSS is the one that you can contribute. Some of the components break on mobile screens.

Ah I see. Understood. Will do!
