### ISSUE TITLE
[ Console ] There a lot of logs in the console due to all the console.log inside. Is it left intentionally or shall I remove those

### ISSUE THREAD

**Issue by AnirudhPanda** [ashutosh1919/masterPortfolio#134]
![issues](https://user-images.githubusercontent.com/66218496/126045831-3fa8c084-e24e-49b5-abfe-cd889bacec4c.PNG)

**Comment by ashutosh1919** [comment]
@AnirudhPanda You can raise PR to remove them.

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda You can raise PR to remove them.

Hey bhaiya,
After I did npm install it looks like it modified the package.lock.json file and now it is showing a huge number of insertions and deletions, should I add that file in gitignore?
A little guidance would help

**Comment by ashutosh1919** [comment]
Yes you can add it.
