### ISSUE TITLE
[BUG] School logo is upside down in the Education Section

### ISSUE THREAD

**Issue by Rammina** [ashutosh1919/masterPortfolio#139]
![upsidedown](https://user-images.githubusercontent.com/49326578/130438318-8ec5749d-8ddb-43f8-a385-6152c4804401.png)

**Comment by ashutosh1919** [comment]
@Rammina , yes this bug is a headache and is not fixed even after 2-3 PRs. Feel free to raise PR to resolve this.

**Comment by Rammina** [comment]
@ashutosh1919, the bug only shows up on the deployed version (live example) but downloading it and running it on the local machine, the logo is upright and is displayed correctly.

**Comment by dhruvkrishnavaid** [comment]
> @Rammina , yes this bug is a headache and is not fixed even after 2-3 PRs. Feel free to raise PR to resolve this.

Done!
