### ISSUE TITLE
all git repo card size should be same

### ISSUE THREAD

**Issue by shreyshreyansh** [ashutosh1919/masterPortfolio#140]
![Screenshot 2021-08-25 092805](https://user-images.githubusercontent.com/53744971/130725298-c16bf98f-e04a-400a-978a-3d915f86c332.png)

**Comment by saiteja13427** [comment]
We can implement this without hard-coding the height using flex. Implemented this on my portfolio. Will raise a PR. Do assign this as well to me @ashutosh1919

**Comment by saiteja13427** [comment]
Raised a PR #198

**Comment by saiteja13427** [comment]
This is solved
