### ISSUE TITLE
I have some issues when trying to run npm start, can anyone help me with this

### ISSUE THREAD

**Issue by nguye3hg** [ashutosh1919/masterPortfolio#143]
**This is the error when I run npm start on git bash** 

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:3000/' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! masterPortfolio@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the masterPortfolio@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoang\AppData\Roaming\npm-cache\_logs\2021-08-27T14_26_57_477Z-debug.log

**Comment by nguye3hg** [comment]
Yes i have already run that

**Comment by ashutosh1919** [comment]
@nguye3hg , can you print out the error log here. I mean content of file `C:\Users\hoang\AppData\Roaming\npm-cache_logs\2021-08-27T14_26_57_477Z-debug.log`

**Comment by nguye3hg** [comment]
How can I print out that can you help me with that too?

**Comment by nguye3hg** [comment]
**This is all my code on git bash I will leave it here** 
hoang@DESKTOP-EL5GVQ1 MINGW64 ~/OneDrive/Desktop/masterPortfolio (master)
$ npm start

> masterPortfolio@0.1.0 start C:\Users\hoang\OneDrive\Desktop\masterPortfolio
> react-scripts start

Starting the development server...

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:3000/' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! masterPortfolio@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the masterPortfolio@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hoang\AppData\Roaming\npm-cache\_logs\2021-08-28T02_35_55_428Z-debug.log

**Comment by nguye3hg** [comment]
**@ashutosh1919 I have try to put the link in my folder and this is the result**
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle masterPortfolio@0.1.0~prestart: masterPortfolio@0.1.0
6 info lifecycle masterPortfolio@0.1.0~start: masterPortfolio@0.1.0
7 verbose lifecycle masterPortfolio@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle masterPortfolio@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\hoang\OneDrive\Desktop\masterPortfolio\node_modules\.bin;C:\Users\hoang\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\hoang\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\MinGW\bin;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Polyspace\R2020a\bin;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\hoang\AppData\Local\Programs\Python\Python39-32\Scripts;C:\Users\hoang\AppData\Local\Programs\Python\Python39-32;C:\Users\hoang\AppData\Local\Microsoft\WindowsApps;C:\Users\hoang\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW\bin;C:\Users\hoang\AppData\Local\GitHubDesktop\bin;C:\Users\hoang\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;C:\Users\hoang\bin\win-sudo\s
9 verbose lifecycle masterPortfolio@0.1.0~start: CWD: C:\Users\hoang\OneDrive\Desktop\masterPortfolio
10 silly lifecycle masterPortfolio@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle masterPortfolio@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle masterPortfolio@0.1.0~start: Failed to exec start script
13 verbose stack Error: masterPortfolio@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid masterPortfolio@0.1.0
15 verbose cwd C:\Users\hoang\OneDrive\Desktop\masterPortfolio
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error masterPortfolio@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the masterPortfolio@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nguye3hg** [comment]
I have fixed all the vulnerabilities and updated all the packages and now it seems to work.
