### ISSUE TITLE
Node GYP Error

### ISSUE THREAD

**Issue by Itz-Hyperz** [ashutosh1919/masterPortfolio#152]
![image](https://user-images.githubusercontent.com/69090660/134380866-60c25f81-1ec3-4982-bca9-cd1a9675a677.png)

Currently on NodeJS V16

**Comment by ashutosh1919** [comment]
@Itz-Hyperz , The issue is not with code but with installation. You don't have Python installed on your system it seems. Please close issue once it is resolved.

**Comment by Erik-Avakian** [comment]
Hi, i have the same issue. i have python 2 and python 3.10 installed.
i have used python for a long time so it can't be python that is the problem

**Comment by Erik-Avakian** [comment]
> @Itz-Hyperz , Hi, i have the same issue. i have python 2 and python 3.10 installed.
i have used python for a long time so it can't be python that is the problem

**Comment by ashutosh1919** [comment]
@Erik-Avakian , In the error screenshot, it explicitly says that "Python not found in PATH". You may have Python but it may not be in PATH.

**Comment by Erik-Avakian** [comment]
@ashutosh1919 aah ok, I will try to fix that then. thank u!

**Comment by Erik-Avakian** [comment]
@ashutosh1919  Thank u! that seems to have fixed that error for me. however, i still get other errors :(
i have opened up my own ticket where it shows my current error messages.
please check it out when you have time :) <33

**Comment by ashutosh1919** [comment]
Resolved as part of #171
