### ISSUE TITLE
TypeError: react__WEBPACK_IMPORTED_MODULE_0__.createContext is not a function

### ISSUE THREAD

**Issue by NirmalSilwal** [ashutosh1919/masterPortfolio#153]
Can someone help me resolve this issue?

Error name: **TypeError: react__WEBPACK_IMPORTED_MODULE_0__.createContext is not a function**

Attaching part of screenshot of the issue after running 
```
npm start
```

![Capture](https://user-images.githubusercontent.com/31946761/135908991-25c6cd28-4296-4f8c-8f85-ef1927e000c3.PNG)

**Comment by ashutosh1919** [comment]
@NirmalSilwal , Have you installed all dependencies using `npm install`?

**Comment by NirmalSilwal** [comment]
Initially all the dependencies were not installed properly using ```npm install``` 

I was getting many warnings. Later  I used **[this package manager](https://github.com/raineorshine/npm-check-updates)** and now it works. 

Thanks
