### ISSUE TITLE
Faced console warnings on 'Autoprefixer is no longer needed for your stylesheet'

### ISSUE THREAD

**Issue by catherinewongg** [ashutosh1919/masterPortfolio#154]
Hi, this doesn't break anything but I faced a lot of these warnings in my console. Do you know how to fix it?

Here's an example....
```
Warning

Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.   

./src/containers/skills/Skills.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/containers/skills/Skills.css)
```

![image](https://user-images.githubusercontent.com/86725803/136221316-b1faef56-e0a0-4e8c-8370-f2cd8c2d1008.png)

**Comment by ashutosh1919** [comment]
@saiteja13427 can you please confirm if these warnings are still there when running `npm i && npm start`

**Comment by saiteja13427** [comment]
@ashutosh1919 I already checked it. I checked on both Firefox and Chrome on my system and did not see this error.

**Comment by ashutosh1919** [comment]
@catherinewongg closing on the basis of @saiteja13427's comment. Please feel free to reopen if the error still persists.
