### ISSUE TITLE
Font of header is displaying differently-  Agustina font not rendered in header

### ISSUE THREAD

**Issue by NirmalSilwal** [ashutosh1919/masterPortfolio#160]
Hello @ashutosh1919, in my portfolio the font of header is displaying differently, as I have not changed any other setting for fonts in any file. 

For your reference - 
## currently displaying in my portfolio

![Capture](https://user-images.githubusercontent.com/31946761/136654832-5d32b269-0a52-4620-84c5-8eba7ebdb562.PNG)

## Expected font

![capture2](https://user-images.githubusercontent.com/31946761/136654835-e57be5d8-f658-4356-ae1d-5467898f985e.PNG)

I see fonts are defined in ```index.css``` but not sure where they are referred. Can you direct me to the solution for Agustina font?
Tagging @dhruvkrishnavaid too :)

Thanks

**Comment by ashutosh1919** [comment]
@NirmalSilwal , [Here](https://github.com/ashutosh1919/masterPortfolio/tree/master/src/assests/fonts) it is. Please close the issue if it is resolved.

**Comment by NirmalSilwal** [comment]
**update** - I found the location (```src/components/header/header.css```) and found that it is currently Agustina font but it is looking just bit different with my name. I tested putting your name in logo header and it was same, just for different name combination that was looking different than what I was expecting. 😃

**Comment by NirmalSilwal** [comment]
@dhruvkrishnavaid you're right, -> ```Since the text is different, this might be the letters that the font developer created.```
