### ISSUE TITLE
Page 'open source' keeps zooming which cann't be zoomed out

### ISSUE THREAD

**Issue by KasRoudra** [ashutosh1919/masterPortfolio#163]
After `npm install` and `npm start` the "open source" page of website keeps zooming automatically resulting into this(Both brave and chrome browser in android): 
![Screenshot_2021-10-18-08-20-13](https://user-images.githubusercontent.com/78908440/137659669-edcfda25-e180-443e-8d20-4fa8a0efa28f.jpeg)
![Screenshot_2021-10-18-08-20-02](https://user-images.githubusercontent.com/78908440/137659671-a0e126ef-f90a-434c-9277-6da2adc8211d.jpeg)

But when I cloned your [website repository](https://github.com/ashutosh1919/ashutosh1919.github.io) and hosted it, I found everything is ok. Now, how to solve my one?

**Comment by abdslam01** [comment]
please have a look  at #167 , it may help you!
