### ISSUE TITLE
Unable to use this project!

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [ashutosh1919/masterPortfolio#173]
Whenever I'm trying to run npm install it's showing some error. what should I do?

**Comment by ashutosh1919** [comment]
@Jyoti-prakash-rout , please take a look at #171 and follow the steps used in that. It should help.

**Comment by Jyoti-prakash-rout** [comment]
@ashutosh1919  Thank you so much for the help. Issue Solved :-)
