### ISSUE TITLE
Lots of warnings as errors when installing 

### ISSUE THREAD

**Issue by Krishpanchal** [ashutosh1919/masterPortfolio#185]
There are lots of warnings and errors while running the command `npm install`

![image](https://user-images.githubusercontent.com/63506149/161278948-eaa2f807-76c6-4e7d-8c9c-957176a40fa9.png)

![image](https://user-images.githubusercontent.com/63506149/161279039-e42d0c9a-cfad-486a-96f3-ef7b2c7f97ad.png)

**Comment by anurag9034** [comment]
updating the version of "node-sass" to "6.0.1" fixed the issue for me!

**Comment by Krishpanchal** [comment]
Thankyou so much brother,
Worked for me too
