### ISSUE TITLE
Switch  pics on the each page?

### ISSUE THREAD

**Issue by Guohao91** [ashutosh1919/masterPortfolio#191]
Hi, Just wonder if it is possible to switch the pics on the left side with my own pics?
If I can do that, in which script file I should update the location info?
![Screenshot from 2022-05-10 14-26-30](https://user-images.githubusercontent.com/54188732/167724673-b9588644-39a4-4782-b488-fe4deb9f61f0.png)

Thanks a lot in advance for any hint!

**Comment by ashutosh1919** [comment]
@Guohao91 you need to create React component [here](https://github.com/ashutosh1919/masterPortfolio/tree/master/src/containers/skills) with the image that you would like to render. Also, you need to change the `skills.filename` attribute in `src/portfolio.js` file which will pick the image component that you created instead of default one.

**Comment by Guohao91** [comment]
hi， @ashutosh1919 
Thanks for reply!
I've been awared of these component files in there, and I know I'll need to update thefilename attributes under skills data[ ].
However I just don't know how to locate the pics I saved?
For example, in /src/containers /skills/DesignImg.js, I just found the <svg
        id="1c51936f-ad83-4493-a1e8-5a7ca1846cda"...> is specific for each assigned picture, 
so I need to undersatnd how to build and use React frame?

**Comment by ashutosh1919** [comment]
You need to wrap the image in a react component. That's it. It is up to you how you want to implement it.

**Comment by Guohao91** [comment]
@ashutosh1919 
Oh oh! Let me find how to wrap a image into a react componenet.
Thank you!

**Comment by ashutosh1919** [comment]
@Guohao91 The app is React App and not React Native app. Why are you using `react-native`? You need to either use react compatible package or implement your own styles.

**Comment by Guohao91** [comment]
Hi, Mr. @ashutosh1919 
I didn't mean have to use react-native...Let me try this: 
how can i get this id attribute for my own local pic?
![image](https://user-images.githubusercontent.com/54188732/167929834-60ee1518-01b6-498b-bd66-a401f360a432.png)

And I actually would prefer to reference to your architecture to load up my local pic. That's it.
But just like I am not familiar with React, that's my problem. Or can you just simply teach how to load up a local pic?
Thanks a lot Sir!
