### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by saiteja13427** [ashutosh1919/masterPortfolio#193]
Proposal for design improvement of experience page especially the **accordions**.

### Reason for change
This component looks odd and doesn't sync with the complete design.

### How can we improve?
1. We can make the corners rounded.
2. Change the color to sync in the theme
3. And few other miscellaneous styling changes if required.

**I would like to take it up if you guys also think that this is required!!**

Attached are the current screenshot and what we can make it (Just to give a rough idea)

![image](https://user-images.githubusercontent.com/40917760/169645059-1b08f33a-7fdf-47fa-8e58-8ecc6024745b.png)

![image](https://user-images.githubusercontent.com/40917760/169646541-7f2fa8ef-736f-47c4-a101-f3adb97bb258.png)

**Comment by ashutosh1919** [comment]
@saiteja13427 Sure please go ahead and raise PR.

**Comment by saiteja13427** [comment]
Done with this issue! So closing it!
