### ISSUE TITLE
Adding Check For Image and Visit Website Button on Education Page

### ISSUE THREAD

**Issue by saiteja13427** [ashutosh1919/masterPortfolio#195]
We should have checks for the presence of institute logo image and website URL.

### Reason
Many of the schools and secondary colleges might not have logos online and websites as well.

### What to change
**For Logo**
1. We can add a check in the code for the logo and if the logo exists, only then we show it, else we just skip it. Currently if there is no logo, it just crashes

**For Visit Website Button**
1. We can have a check and show the visit website button only if it exists. Currently, the button shows up even if the URL is not given.

**I am willing to take this up as well @ashutosh1919**

**Comment by ashutosh1919** [comment]
@saiteja13427 yes I agree. We initially planned doing it but never got to it. Please feel free to raise PR. Meanwhile, Assigning to you

**Comment by saiteja13427** [comment]
Raised a PR #197

**Comment by saiteja13427** [comment]
This is done
