### ISSUE TITLE
git_data_fetcher.js returns an Error when executed for the second time

### ISSUE THREAD

**Issue by danielmarostica** [ashutosh1919/masterPortfolio#21]
`Error occured in pinned projects 2 {}
{}
{}
{}
`

**Comment by ashutosh1919** [comment]
@danielmarostica , I am not getting that kind of error. Since @danielmarostica , you are active contributor to the repository, can you raise the PR to resolve the issue? Also, please paste any console error logs if you are getting any. :)

**Comment by Sagyam** [comment]
@danielmarostica  I was getting this exact error turns out I has a typo in my username.
BTW did you find a way to add custom icons? It seems like ther's no way around fontAwesome icons?

**Comment by danielmarostica** [comment]
https://github.com/iconify/iconify/issues/32

**Comment by suyesha07** [comment]
Im getting the exact error how to solve this ??

**Comment by ashutosh1919** [comment]
@danielmarostica or @Sagyam , Can one of you help @suyesha07 ? 

@suyesha07 , You can post a screenshot of the error or you can paste the entire error stack here.

**Comment by NirmalSilwal** [comment]
I am getting similar isssue while trying to fetch my github profile info to the portfolio using ```node git_data_fetcher.js```

I followed the given steps - generated new token with all permissions and added that token as suggested along with my username. But I am getting this exception message. Can someone help on this? 

Tagging @ashutosh1919  @danielmarostica @Sagyam 

Attaching screenshot of the issue -
![Capture](https://user-images.githubusercontent.com/31946761/136106577-636473f1-6147-4405-a6d8-b7079474a181.PNG)

**Comment by ashutosh1919** [comment]
@NirmalSilwal , I think you do not have support for JS other than ES6. The `git_data_fetcher` doesn't use ES6 so that may be the problem.

**Comment by NirmalSilwal** [comment]
Hello @dhruvkrishnavaid can you also look after this issue?

**Comment by NirmalSilwal** [comment]
Thank, looking forward to the solution.

**Comment by Saurabh-212800** [comment]
@ashutosh1919 @dhruvkrishnavaid I am also getting this error please tell me how I can solve This error. I am doing all the steps but node git_data_fetcher.js is throwing error like this .... 
![IMG20211128121154](https://user-images.githubusercontent.com/73703031/143733012-ccb9365f-7004-467b-9539-60be32067096.jpg)
Please let me know the solution ..

**Comment by dhruvkrishnavaid** [comment]
> @ashutosh1919 @dhruvkrishnavaid I am also getting this error please tell me how I can solve This error. I am doing all the steps but node git_data_fetcher.js is throwing error like this .... ![IMG20211128121154](https://user-images.githubusercontent.com/73703031/143733012-ccb9365f-7004-467b-9539-60be32067096.jpg) Please let me know the solution ..

You need to run `node git_data_fetcher.mjs` in the console.

**Comment by Saurabh-212800** [comment]
I had done all the required Changes but I am getting this error after pushing code to GitHub. @ashutosh1919 @dhruvkrishnavaid ....
![Screenshot_2021-12-08-16-08-00-42_e307a3f9df9f380ebaf106e1dc980bb6](https://user-images.githubusercontent.com/73703031/145194396-7dd3704c-b547-46d1-9666-d2fb8426946d.jpg)

**Comment by ashutosh1919** [comment]
@Saurabh-212800 you need to remove `CNAME` file from the project because it points to my domain name. You also need to configure gh-pages. You can take a look at the video mentioned in the project README.

**Comment by Saurabh-212800** [comment]
> @Saurabh-212800 you need to remove `CNAME` file from the project because it points to my domain name. You also need to configure gh-pages. You can take a look at the video mentioned in the project README.

@ashutosh1919  can you please share that video link here .

**Comment by ashutosh1919** [comment]
@Saurabh-212800 , https://www.youtube.com/watch?v=IwBS39TOmpA&t=557s

**Comment by mayureshagashe2105** [comment]
#156 doesn't seem to fix #21. Getting the same error.
![2022-01-25 (2)](https://user-images.githubusercontent.com/75118658/150986645-b2609cdc-a962-48e0-8393-03ac58ecadca.png)

**Comment by mayureshagashe2105** [comment]
@ashutosh1919 @dhruvkrishnavaid please look into it.
Thank you!

**Comment by dhruvkrishnavaid** [comment]
@mayureshagashe2105 You seem to use environment variables but you have not configured it properly. 

Please configure the `dotenv` package. 🙂

**Comment by mayureshagashe2105** [comment]
Thank you! Configured it correctly, now, it's working

**Comment by ashutosh1919** [comment]
@all-contributors add @dhruvkrishnavaid for question .

Thank you so much @dhruvkrishnavaid for answering questions.

**Comment by pcodesdev** [comment]
To ensure the .env file is correctly formatted, double-check that the two lines defining GITHUB_TOKEN and GITHUB_USERNAME don't have semicolons at the end. The correct format should look like this:

```
GITHUB_TOKEN=your_token_here
GITHUB_USERNAME=your_username_here
```

This small adjustment can make a big difference in how the environment variables are read and used by the application. It's a common oversight that can lead to unexpected behavior, so it's always worth verifying.
