### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by danielmarostica** [ashutosh1919/masterPortfolio#22]
Hi Ashutosh, thanks for the tutorial! It was the only one friendly enough for beginners.

I've been trying to make it work, but so far had no success. 

Should I clone your repository or my fork? Should I make a copy of the folder contents and git init inside a "virgin" one?

What does git_data_fetcher.js do? It does not update package.json, as I had to do it manually.

What is the "generated code" you refer to, that I should push to the /danielmarostica.github.io repo? Only the node_modules/? The data_fetcher, for example, has tokens, so it can't be pushed.

At the final step, github does not allow me to change from master to gh-pages. It seems that it only does if I change the repository name to anything, then link the page to the branch, and then rename again to /danielmarostica.github.io. 

I tried many times, as it is my first attempt at nodejs. The farthest I could get was a blank page with the title of the portfolio.

Thanks!

**Comment by th3c0d3br34ker** [comment]
Hey @danielmarostica  welcome to the world of JavaScript. 
1. You could fork/download as zip the source code, depends on what you want. If you want to use if just once and make a portfolio then I would suggest you to download as zip.
2. The git_data_fetcher just gathers data from your github account and allows you to put that data in your portfolio. If you head on the open source section, you would get what it does.
3. The generated code refers to the `build` folder that is produced by react scripts. Once you are done making changes, run `npm run build` .
4. GitHub does allow you to change the master branch to gh-pages...  [see here](https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch). If you still can't figure out, just upload the contents `build` folder in your master branch.

I hope this solves most of your problem. If again run into problems feel free to ask. 😄

**Comment by danielmarostica** [comment]
Hey @th3c0d3br34ker, awesome tips, it worked right away! I'd suggest a few changes in the Readme file to make future padawan's lives easier hehe

**Comment by danielmarostica** [comment]
But I insist on this: even though you change the default branch to gh-pages, github does not allow anything other than master branch for the user page (user.github.io)

https://github.com/fastai/fastpages/issues/119#issuecomment-591025246

**Comment by ashutosh1919** [comment]
> But I insist on this: even though you change the default branch to gh-pages, github does not allow anything other than master branch for the user page (user.github.io)
> 
> [fastai/fastpages#119 (comment)](https://github.com/fastai/fastpages/issues/119#issuecomment-591025246)

@danielmarostica , sorry that you faced the issue and Thank you so much @th3c0d3br34ker for giving assisatnce here. I got to know about this issue recently and working on it to resolve.

If you want to contribute to the project doc, feel free to raise PR for README.

Thanks again for raising the issue.

**Comment by danielmarostica** [comment]
@ashutosh1919 I will do so! I think my experience of building it out of zero experience with js will help.

**Comment by th3c0d3br34ker** [comment]
Yes, as @danielmarostica pointed out that you can't change the master branch of the this special repository only.

**Comment by ashutosh1919** [comment]
@danielmarostica , If you are rasing PR then keep following things in mind.

(1) If the repository is special, then push the code in branch `develop` and build in master branch. Then enable gh-pages on master.
(2) If the repository is not special, then whatever described right now will work

**Comment by danielmarostica** [comment]
You mention "Please don't use any other names" for the repository name. Why?

Keeping that in mind, is this still valid?
(2) If the repository is not special, then whatever described right now will work

**Comment by ashutosh1919** [comment]
Yes, I meant that if you are creating special repo, don't use any other name. You can use whatever you want for (2).

**Comment by ashutosh1919** [comment]
@danielmarostica , Please close this issue if you don't have any more questions.
