### ISSUE TITLE
MODULE_NOT_FOUND in node git_data_fetcher.mjs

### ISSUE THREAD

**Issue by febincherianjohn** [ashutosh1919/masterPortfolio#226]
![image](https://user-images.githubusercontent.com/108618086/177547993-528d7e00-fea1-48c1-b3c4-8a95f4a6cd97.png)
i changed file to git_data_fetcher.mjs as you said but still its showing the same error...kindly help

**Comment by saiteja13427** [comment]
Do check if the file name is correct. The file name is already `git_data_fetcher.mjs` what did you change?

**Comment by febincherianjohn** [comment]
i had earlier converted the file to .js and tried to node it...so ashuthosh told me to keep the file name as .mjs

**Comment by febincherianjohn** [comment]
solved

**Comment by febincherianjohn** [comment]
./src/pages/projects/Projects.js
Module not found: Can't resolve '../../shared/opensource/publications.json' in 'C:\masterPortfolio-master\src\pages\projects'

pls help me solve this also

**Comment by saiteja13427** [comment]
Did you delete the publications.json file?

**Comment by febincherianjohn** [comment]
> Did you delete the publications.json file?

yes I did

**Comment by saiteja13427** [comment]
Navigate to src/pages/projects/Projects.js

Comment line number 11 and 61-88

**Comment by febincherianjohn** [comment]
thanx & done

**Comment by saiteja13427** [comment]
Awesome
