### ISSUE TITLE
OPENSOURCE

### ISSUE THREAD

**Issue by febincherianjohn** [ashutosh1919/masterPortfolio#227]
Can someone please tell me in which all files and what changes i need to make to remove opensource page

**Comment by ashutosh1919** [comment]
@saiteja13427 please help him

**Comment by saiteja13427** [comment]
@febincherianjohn follow the steps
1. Navigate to src/components/header/Header.js
2. Comment out lines 87 to 98
The opensource page will be removed from the navbar and that will be good enough i guess

**Comment by febincherianjohn** [comment]
it worked ..thankyou very much
