### ISSUE TITLE
experience page color

### ISSUE THREAD

**Issue by febincherianjohn** [ashutosh1919/masterPortfolio#228]
![image](https://user-images.githubusercontent.com/108618086/177602420-4fb4b6c3-61f3-4b7d-afbe-ac77d80a3b9f.png)
![image](https://user-images.githubusercontent.com/108618086/177602531-98d26379-fdcf-4ecd-bcf6-54a74a3f17b5.png)
hey how to make the work internship volunteership white like it is in the second image

kindly help if possible.......thankyou very much

**Comment by ashutosh1919** [comment]
change background color.

cc @saiteja13427

**Comment by saiteja13427** [comment]
@febincherianjohn Follow these steps
1. Navigate to src/containers/experienceAccordion/ExperienceAccordion.js
2. At line 21, replace `${theme.white}` with "#fff"
3. This will do the job. 

Let me know if you face any issue!
