### ISSUE TITLE
How to enter URL for publications

### ISSUE THREAD

**Issue by Mehta-Parth** [ashutosh1919/masterPortfolio#236]
Dear Community,

I am unable to find place where I can add URL for my Publications. Pls help.

Regards,
Parth

**Comment by ashutosh1919** [comment]
@saiteja13427 can you please help @Mehta-Parth?

**Comment by saiteja13427** [comment]
@Mehta-Parth you can just go to `src/shared/opensource/publications.json` and in each data block, you can add a url key, value pair like `url: <your publication url>`.

That should make the title of the publication clickable and will redirect to the url you gave.

Let me know if you face any trouble!

**Comment by saiteja13427** [comment]
Did that work @Mehta-Parth

**Comment by saiteja13427** [comment]
I hope that worked @Mehta-Parth 

@ashutosh1919 I think we need some refactoring on the publications.

Shall we move publications from shared/publications.json to portfolio.js only?

**Comment by ashutosh1919** [comment]
@saiteja13427 Yes we can do that. Anyways, most of the people using our template may not have many publications

**Comment by saiteja13427** [comment]
This issue now stands closed.

@Mehta-Parth please feel free to open another issue if you still have some problem!
