### ISSUE TITLE
Remove Blog Section 

### ISSUE THREAD

**Issue by rajesh1421** [ashutosh1919/masterPortfolio#238]
C:\Users\masterPortfolio\src\portfolio.js and C:\Users\masterPortfolio\src\pages\contact\BlogsImg.js  in this path I remove blog section use {/* ... */} or Erase code.
Page shows some errors  
The Error Is :
×
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Contact`.
▶ 28 stack frames were collapsed.

**Comment by ashutosh1919** [comment]
@rajesh1421 I saw your comment in another issue. I think the issue is resolved. Please reopen if you think it's not fixed yet.
