### ISSUE TITLE
No portfolio

### ISSUE THREAD

**Issue by hilldba** [ashutosh1919/masterPortfolio#243]
Local Host show portfolio after nom start but when I try to go to internet username.GitHub.io shows read me.md

What am I doing wrong

**Comment by saiteja13427** [comment]
Can you share the link and can you tell me the steps you followed please.

**Comment by hilldba** [comment]
If you go here and install node j and react you get a local profile that works fine. But with my domain drcyber.net I just get the readme.md file not the portfolio like locally. 


Tim

**Comment by ashutosh1919** [comment]
@hilldba If you exclude the README file from the build and only push the content of `build` when you push that to deployment. I think it should fix it.

**Comment by hilldba** [comment]
I have remove the readme.md on my local reposity and with npm start my website come up fine either with the file gone or in the local but when I have it in the master branch it comes up with the readme.md home page but when I delete it I get a 404 my website is drcyber.net and is fully in cloud flare had it working this morning and started acting up this afternoon. Do you mind taking a look   Ty   https://github.com/hilldba/hilldba.github.io.git

**Comment by hilldba** [comment]
I have fixed it.  Was a simple one. Had to add a / in package.json to activate the actually node app and npm run build thank you

**Comment by hilldba** [comment]
All the site work when deploy but Education what could it be?

**Comment by Rajesh-A1** [comment]
> I have fixed it. Was a simple one. Had to add a / in package.json to activate the actually node app and npm run build thank you

Can you Explain more about that. I'm also facing this issue
