### ISSUE TITLE
In Search box type open source it shows the page 

### ISSUE THREAD

**Issue by rajesh1421** [ashutosh1919/masterPortfolio#245]
Open Source remove from header but , In Search box type open source it shows the page ,

**Comment by saiteja13427** [comment]
How did you remove the open source page? @rajesh1421

**Comment by rajesh1421** [comment]
In Header.js file     
          {/*<li>
                <NavLink
                  to="/opensource"
                  tag={Link}
                  activeStyle={{ fontWeight: "bold" }}
                  style={{ color: theme.text }}
                  onMouseEnter={(event) => onMouseEnter(event, theme.highlight)}
                  onMouseOut={(event) => onMouseOut(event)}
                >
                  Open Source
                </NavLink>
              </li>*/}
I use  {/*___*/}  this comment tag sir.

**Comment by rajesh1421** [comment]
Thank sir , It's work
