### ISSUE TITLE
Github pages showing content of README.md instead of website's content 🙁

### ISSUE THREAD

**Issue by Nuub32User** [ashutosh1919/masterPortfolio#25]
![Screenshot_20200724-092502_Brave](https://user-images.githubusercontent.com/47206700/88359250-93afa280-cd8f-11ea-8734-932606acd22a.png)

Here is the repo link - https://github.com/Nuub32User/nuub32user.github.io

Urgent Help Needed 😔 I am beginner

**Comment by ashutosh1919** [comment]
You have set gh-pages to master branch and not gh-pages.

**Comment by Nuub32User** [comment]
> You have set gh-pages to master branch and not gh-pages.

How to fix it sar .. 🙁 plz guide me

**Comment by ashutosh1919** [comment]
Settings tab of your repository. Go down to Github Pages and select branch as gh-pages. then ru your website and press Ctrl+Shift+R

**Comment by Nuub32User** [comment]
Finally 😍 fixed .. by that step.. Thanks pro sar
