### ISSUE TITLE
Search Engine Optimization Not Working??

### ISSUE THREAD

**Issue by chandrakanth-gudavalli** [ashutosh1919/masterPortfolio#252]
I have generated my github portfolio (https://chandrakanth-gudavalli.github.io/#/) using your template.

I want to make this page show up if some one type my name on google. May I know what should I do for that?

My portfolio: [https://chandrakanth-gudavalli.github.io/#/](https://chandrakanth-gudavalli.github.io/#/)

PS: This is a great repo. Thanks for maintaining this.

**Comment by ashutosh1919** [comment]
@chandrakanth-gudavalli this totally depends upon Google's ranking algorithm. Your ranking is not only dependent on the content but also on the traffic. Please feel free to ask more questions here but this issue is out of scope of this repo.

**Comment by chandrakanth-gudavalli** [comment]
Thanks for the prompt reply. 

I have seen a [pull request on SEO](https://github.com/ashutosh1919/masterPortfolio/pull/108) specifically for SEO. So, I thought I can make this happen easily.

Are there any tips that we can use to make google rank the github.io page at the top?
