### ISSUE TITLE
Support, Terms Of Service, Privacy policy Pages 

### ISSUE THREAD

**Issue by imkunalshah** [ashutosh1919/masterPortfolio#286]
New pages like support, terms of service and privacy policy which can be opened from the footer

**Comment by saiteja13427** [comment]
@imkunalshah I am not sure if these pages will make sense on a portfolio website.

What do you think @ashutosh1919

**Comment by ashutosh1919** [comment]
@imkunalshah , I agree with @saiteja13427 . Having Privacy policy on the portfolio doesn't make much sense to me. Closing it as of now. But feel free to reopen this if you have more granular comments about it.
