### ISSUE TITLE
cannot get github project data , error in git_data_fetch.mjs  "{} {} Error occured in pinned projects 2 {} {}"

### ISSUE THREAD

**Issue by AmanSarraf** [ashutosh1919/masterPortfolio#301]
#  `dotenv` seem to be working, also tried all the previous fixes from similar closed PR but nothing helped.

![image](https://github.com/ashutosh1919/masterPortfolio/assets/90839355/1d4249d2-7a4e-4144-98ce-9760711b4bff)

**Comment by saiteja13427** [comment]
@AmanSarraf Why is there a semicolon after the logged github username?
Did you add semicolon after username in env?

**Comment by AmanSarraf** [comment]
yes , it had a semicolon there , removed it and now the problem is resolved
