### ISSUE TITLE
Not everyone would want to give a nickname , so if nickname is not provided an "()" bracket is being rendered . 

### ISSUE THREAD

**Issue by Ac-Srikanth** [ashutosh1919/masterPortfolio#31]
This is not exactly an issue , but can i raise an PR regarding this ?

**Comment by ashutosh1919** [comment]
@Ac-Srikanth Feel free to raise PR to resolve this issue. Btw, good observation. This is indeed a problem in my opinion.

**Comment by danielmarostica** [comment]
Hi @Ac-Srikanth,

Go to /src/containers/greeting/Greeting.js and comment these lines:

> {/* <h2 className="greeting-nickname" style={{ color: theme.text }}>
> ( {greeting.nickname} ) </h2> */}

**Comment by rahulrachh** [comment]
@Ac-Srikanth, for now, you can go to ``src\containers\greeting\greetings.js`` and comment lines 20 to 22. This would do to hide the brackets.

**Comment by tamojit-123** [comment]
@ashutosh1919  @rahulrachh in replace of the nickname an waving emoji can be given by importing it in portfolio.js.

**Comment by rasam-hossain** [comment]
> 
> 
> @ashutosh1919 @rahulrachh in replace of the nickname an waving emoji can be given by importing it in portfolio.js.

This is a good suggestion too.

**Comment by ashutosh1919** [comment]
@tamojit-123 feel free to raise a PR to fix this as you described. I liked an idea.

**Comment by tamojit-123** [comment]
@ashutosh1919 I did a PR regarding this issue.
please have a look
**URL**: [https://github.com/ashutosh1919/masterPortfolio/pull/105#issue-551803932](url)

**Comment by saiteja13427** [comment]
PR #284 fixes this issue. Marking it closed!
