### ISSUE TITLE
Running on local host but blank on github pages

### ISSUE THREAD

**Issue by Saqib-Ansari786** [ashutosh1919/masterPortfolio#310]
the issue is, Website is running on local host but whenever i deployed on github pages. it shows that deployment is successful but show blank pages.

**Comment by vinitsingh-13** [comment]
I can solve this issue

**Comment by ashutosh1919** [comment]
@Saqib-Ansari786 I think I have explained about this in detail in [this video](https://www.youtube.com/watch?v=IwBS39TOmpA&t=557s)

Feel free to reopen this issue if not solved yet.

**Comment by Saqib-Ansari786** [comment]
Okay. Thanks for explaining this.
