### ISSUE TITLE
Running on local but blank on GitHub Pages

### ISSUE THREAD

**Issue by MananShah3654** [ashutosh1919/masterPortfolio#314]
the issue is, Website is running on a local host but whenever I deploy it on GitHub pages. it shows that deployment is successful but shows blank pages. @ashutosh1919 
![Screenshot 2023-08-16 203327](https://github.com/ashutosh1919/masterPortfolio/assets/91079692/cb223c77-3a1a-461c-a542-f711aebbc31a)

**Comment by ashutosh1919** [comment]
@MananShah3654 Most probably there should be some config issue. Please watch this video and see if you have followed all steps correctly: https://youtu.be/IwBS39TOmpA?si=mnDgU_SUXUBPpuiu

**Comment by AdityaPartole** [comment]
"Hi @MananShah3654 ,

I noticed you've faced and resolved the issue of deploying a website to GitHub Pages with blank pages. Could you please share how you tackled it? I'm encountering the same problem.

**Comment by Shiro-LK** [comment]
@MananShah3654  I am also encountering the same issue, could you share how you solve this?

**Comment by Shiro-LK** [comment]
I tried to just use the default template, by changing only the "homepage" parameters in package.json and i also have the blank page on github page. But it works well locally

**Comment by Shiro-LK** [comment]
@AdityaPartole  I think you might have forget like me the "https://" in homepage. It was the issue i had.

**Comment by ashutosh1919** [comment]
Closing the issue. Please reopen if not resolved yet.
