### ISSUE TITLE
how to change anything after deploying Successfully

### ISSUE THREAD

**Issue by rajesh9943** [ashutosh1919/masterPortfolio#315]
Hi @ashutosh1919 
this master portfolio great project and thanks for Sharing it with us.
I am a newbie to node js. I successfully deployed my master portfolio. but i want to change one.
Again, I do the same process but the deployment cannot be successful
can you Please help to solve this issue
![Screenshot (72)](https://github.com/ashutosh1919/masterPortfolio/assets/98160008/9d9c3988-91c6-4703-8b32-0490f0a461a2)

**Comment by dhruvkrishnavaid** [comment]
The origin URI is not specified.
Run `git remote add origin https://github.com/{username}/{repo_name}.git` first then try running `git push origin master` again

**Comment by ashutosh1919** [comment]
@rajesh9943 I think @dhruvkrishnavaid's comment would help you push the changes to repo. I explained in detail in [this video](https://www.youtube.com/watch?v=IwBS39TOmpA&t=557s)

Feel free to reopen with more details if the issue is not yet resolved

**Comment by rajesh9943** [comment]
Hi @dhruvkrishnavaid @ashutosh1919 
I facing an issue in updating masterportfolio. 
using this cmts git remote add origin https://github.com/rajesh9943/rajesh9943.github.io.git
and git push origin master 
Error :
$ git remote add origin https://github.com/rajesh9943/rajesh9943.github.io.git
error: remote origin already exists.

**Comment by dhruvkrishnavaid** [comment]
> Hi @dhruvkrishnavaid @ashutosh1919 
> I facing an issue in updating masterportfolio. 
> using this cmts git remote add origin https://github.com/rajesh9943/rajesh9943.github.io.git
> and git push origin master 
> Error :
> $ git remote add origin https://github.com/rajesh9943/rajesh9943.github.io.git
> error: remote origin already exists.


Please share the output after running `git remote -v`

**Comment by rajesh9943** [comment]
sure, @dhruvkrishnavaid 
origin  https://github.com/rajesh9943/rajesh9943.github.io.git (fetch)
origin  https://github.com/rajesh9943/rajesh9943.github.io.git (push)

**Comment by dhruvkrishnavaid** [comment]
> sure, @dhruvkrishnavaid 
> origin  https://github.com/rajesh9943/rajesh9943.github.io.git (fetch)
> origin  https://github.com/rajesh9943/rajesh9943.github.io.git (push)

Your git origin has already been set. Perhaps you're running `git add remote` twice. Just ignore the error and skip forward to the next step.
