### ISSUE TITLE
latest version of nodejs

### ISSUE THREAD

**Issue by Saurabh-001-S** [ashutosh1919/masterPortfolio#322]

**Comment by Saurabh-001-S** [comment]
i forked this project to my github account and then clone it in my pc then i run npm install so it install all packages that need the projects, but when i run the app it when developement server start and then instantly close the development server.

**Comment by autumn-absconds** [comment]
> i forked this project to my github account and then clone it in my pc then i run npm install so it install all packages that need the projects, but when i run the app it when developement server start and then instantly close the development server.

because this project uses the earlier version of node js. 
You can switch between different versions node and npm  by using **nvm**
or simply install a earlier version of node on your system.

**Comment by ashutosh1919** [comment]
@Saurabh-001-S , I think @autumn-absconds's comment should help you.

Please reopen the issue if it is yet not resolved.

**Comment by Saurabh-001-S** [comment]
Yes it resolve thanks @autumn-absconds
