### ISSUE TITLE
digital envelope routines::unsupported issue on Node.js v18.18.2

### ISSUE THREAD

**Issue by mmar58** [ashutosh1919/masterPortfolio#328]
Every time I open the project and tries to run the project on node js 18.18.2, this issue is showing until I run the command `set NODE_OPTIONS=--openssl-legacy-provider`.

And I have to run the command before start every time I open the project. So is there any way to fix this issue, so that I don't need to run this command every time?

**Comment by GitSankhya** [comment]
There's a few different things you could do but I found the easiest way was to edit the package.json scripts entry to
`` "start": "set NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",``
