### ISSUE TITLE
PNGs/SVGs instead of iconify

### ISSUE THREAD

**Issue by danielmarostica** [ashutosh1919/masterPortfolio#33]
Some icons do not exist at iconify.design (scikit-learn, for example).

It would be great if it was possible to insert other images instead, in these sections:

![image](https://user-images.githubusercontent.com/3595998/88485202-812d9880-cf4a-11ea-98b5-ae555343ad8a.png)

**Comment by dhruvkrishnavaid** [comment]
Iconify now has [scikit-learn icon](https://icon-sets.iconify.design/simple-icons/scikitlearn/).
#219 updates Iconify to the latest version as of now, hence you can now include it in your portfolio.

**Comment by dminkovski** [comment]
@saiteja13427 inserting images still an idea? I would love to take a look at this then 😄

**Comment by saiteja13427** [comment]
@dminkovski yes, it would be great if you can implement this.

Make sure that existing iconify option also works though!

**Comment by dminkovski** [comment]
@saiteja13427 Hey yes I will gladly have a look and try this out 😄

**Comment by saiteja13427** [comment]
@dminkovski Awesome, I am assigning it to you then, reach out to me if you face any issue as such!

**Comment by saiteja13427** [comment]
Closing the issue as PR #288 adds the required functionality.
