### ISSUE TITLE
I have created a better version of it here https://github.com/kritarth2121/masterPortfolio hosted here kritarth.netlify.app

### ISSUE THREAD

**Issue by kritarth2121** [ashutosh1919/masterPortfolio#341]
What I have done
Added Typescript
Added dialogbox for projects
Added a better backround animation
added a better dynamic splash screen

**Comment by ashutosh1919** [comment]
@kritarth2121 Please create PR if you want to contribute to the original project. feel free to reopen this issue if you want to do so.
