### ISSUE TITLE
Node JS Icon is not visible

### ISSUE THREAD

**Issue by Ravikumar10593-hub** [ashutosh1919/masterPortfolio#343]
Node Js icon is not visible
![image](https://github.com/ashutosh1919/masterPortfolio/assets/65507584/14a3599f-1a23-4b51-8cf7-6d89723d7831)

To reproduce the error:
1. Go to https://ashutoshhathidara.com/#/home
2. Scroll down to full-stack development
3. The Node Js Icon is not visible as you can see in the above screenshot

**Comment by Ravikumar10593-hub** [comment]
can you please assign this to me:
I already have an SVG for the Node JS: https://www.vectorlogo.zone/logos/nodejs/nodejs-icon.svg

**Comment by ripu2** [comment]
Is it still unassigned ?

**Comment by ashutosh1919** [comment]
<img width="577" alt="Screenshot 2024-11-11 at 5 46 15 PM" src="https://github.com/user-attachments/assets/24945315-7745-4575-8504-9c136f30b0ce">

It shows now.
