### ISSUE TITLE
Adding pages to describe projects in more details

### ISSUE THREAD

**Issue by Shiro-LK** [ashutosh1919/masterPortfolio#345]
First of all, thank you for sharing your template to help creating customizable portfolio.

I don't have experience in creating portfolio/website, so apologize in advance if the question looks "dumb".

I was looking at the project section, and wanted to add a "description" page for each of the project instead of linking them to a github link for example. I was wondering how I could do that as i did not find how to do it. The description page would be similar to a blog page where you describe the project and provide images as well. I suppose HTLM to make the page would make sense? However, how do i incorporate these HTML page inside the project? and how do i keep the same background/template than the current portfolio template for the HTML page?

I would welcome any advices as I don't know much about it.

**Comment by saikiran6694** [comment]
You have to make custom components which will dynamically render the data of each project. For this you just have to create a single route but it will have an id which will dynamically changes based on the project which you have clicked. Once the router moves to that page can can send all the relevant data for that particular project to this route, which you can render without creating a different component for every project present in the projects section.

**Comment by saikiran6694** [comment]
Can i contribute to this issue ? please assign it to me

**Comment by ashutosh1919** [comment]
@Shiro-LK @saikiran6694 Currently we fetch the pinned repositories as projects from GitHub account. We are not planning to expand it to render the entire readme files (it might increase the memory overhead of the website although doable).

@saikiran6694 you might want to work on upgrading the node/npm dependencies versions to the latest. It would help the project stay up-to-date with the new versions
