### ISSUE TITLE
Correct position of University logo which is upside down

### ISSUE THREAD

**Issue by mrjatinchauhan** [ashutosh1919/masterPortfolio#35]
Correct position of **University logo** which is **upside down** in **Education section** of Header

Existing Element
```html
<img src="/masterPortfolio/static/media/iiitk_logo.c350d799.png" alt="IIITDM Kurnool" style="max-width: 100%; max-height: 100%; transform: scale(-0.5);">
```

Element replacing for **Correct position of Degrees Received Icon**
```html
<img src="/masterPortfolio/static/media/iiitk_logo.c350d799.png" alt="IIITDM Kurnool" style="max-width: 100%; max-height: 100%; transform: scale(0.5);">
```

You'll notice that _CSS style_ `transform` changed to to `scale(0.5)` which displays university logo (iiitk_logo.c350d799.png) in correct position instead of upside down.

**Comment by th3c0d3br34ker** [comment]
Hey @mrjatinchauhan it seems that I can replicate the issue. Could you please add a screen shot?

**Comment by ashutosh1919** [comment]
@mrjatinchauhan , Please raise Pull request to do so.

**Comment by mrjatinchauhan** [comment]
Before that I'm making a Pull request(#36) to fix a patch for low, medium and high vulnerabilities

**Comment by mrjatinchauhan** [comment]
Fixes university logo position with new PR. #36
