### ISSUE TITLE
Google scholar profile doesn't render correctly

### ISSUE THREAD

**Issue by saireddythfc** [ashutosh1919/masterPortfolio#353]
I added a google profile object in the social media links. However, there is an issue in rendering the icon, while all others seem to work fine.
<img width="1265" alt="Screenshot 2024-03-25 at 6 46 16 PM" src="https://github.com/ashutosh1919/masterPortfolio/assets/48598468/d17bcb63-f591-4e2d-9e62-85f9824baf26">

Here's what I added to the socialMediaLinks object in portfolio.js.
{
    name: "google-scholar",
    link: "https://scholar.google.com/citations?user=myuserid",
    fontAwesomeIcon: "fa-google-scholar", // Reference https://fontawesome.com/icons/google-scholar?style=brands
    backgroundColor: "#4285F4", // Reference https://simpleicons.org/?q=google+sc
  },

**Comment by ashutosh1919** [comment]
@saireddythfc font-awesome might not have the logo.

**Comment by saireddythfc** [comment]
You mean in the reference link that I mentioned? 
I downloaded the svg and put it in masterPortfolio/src/assests/font-awesome/svgs/brands
Both the reference links of font-awesome and backgroundColor are working.

Something I'm missing?
