### ISSUE TITLE
package.json file edit

### ISSUE THREAD

**Issue by pcodesdev** [ashutosh1919/masterPortfolio#367]
The instructions given on editing package.json file are not clear and I am having a challenge trying make the suggested edits.

**Comment by ashutosh1919** [comment]
@pcodesdev please refer to the [youtube playlist](https://www.youtube.com/watch?v=CBVwbcR2hQ8&list=PLR0CKdeR_FysqzwdI1Xk0MgTqufJXLoYb&pp=gAQBiAQB) for detailed instructions.
