### ISSUE TITLE
I am not able to fetch my github projects despite of fetching the tokens and .env

### ISSUE THREAD

**Issue by 0Sujal** [ashutosh1919/masterPortfolio#374]
![image](https://github.com/user-attachments/assets/2f044646-869f-48c7-90ca-7ff546059cc4)

I cannot fetch my GitHub projects, despite fetching the tokens and username into.env fike, I have done all the checks but nothing works

**Comment by pcodesdev** [comment]
@0Sujal I am having the same problem. Kindly let me know if there is any solution to this problem

**Comment by pcodesdev** [comment]
@0Sujal make sure that your .env file code has no semicolons at the end of both the 2 lines of code. I hope this helps

**Comment by 0Sujal** [comment]
@pcodesdev Yaa thanks , I was about to tell you the same thing

**Comment by pcodesdev** [comment]
@0Sujal Thank you. You can now close this issue.
