### ISSUE TITLE
Can't use non-brand icons in SocialMediaLinks 

### ISSUE THREAD

**Issue by Adamou02** [ashutosh1919/masterPortfolio#381]
Is there a way to use icons that are not in brands style (as fa-envelope)

![image](https://github.com/user-attachments/assets/28208289-a100-417a-8ab2-156ac8f2fdc7)

Result : 

![image](https://github.com/user-attachments/assets/b2305ce9-9c04-46c3-a87b-b608425441d5)

**Comment by ashutosh1919** [comment]
@Adamou02 `fa-regular fa-envelope` should work.
