### ISSUE TITLE
Contributions and PR sections

### ISSUE THREAD

**Issue by guilyx** [ashutosh1919/masterPortfolio#5]
Hi,

First off I'd like to put out there that I'm an absolute noob at web technologies/development, which should help with how we communicate.

So, I haven't tried building yet ( and I think you should probably add a readme section on how to build the site ), but I am curious about the Contributions and PR sections of the Open Source page. Is there any way to retrieve only the dependencies from this and get the same trackers ?

Are those trackers updated often ? Is there a way to just embed them in the HTML part of a site ?

Those questions may come up ridiculous but again, I'm from Embedded/Robotics and have never touched this before haha.

Thanks anyways !

( and props for this, developerPorfolio looked cool but masterPortfolio has ridiculously cool additions ! )

**Comment by ashutosh1919** [comment]
HI @guilyx , Thanks for creating issue. 
-  You can run your site locally using `npm install` && `npm start`.
-  I am working on customizing the website. It is 90% customization but I still have to work on 10%.
-  No, You can't embed code in HTML because the website is built on React.

**Comment by guilyx** [comment]
Hi, thanks for the info.

How did you retrieve the github info in `shared/opensource/*.json` ?

**Comment by ashutosh1919** [comment]
I have written scripts to fetch data but did not upload them into this repo because it contains TOKEN and other private info.

**Comment by guilyx** [comment]
Ok ! Thanks anyways ;)
