### ISSUE TITLE
While adding new social media icons apart from the current ones hover effect is missing

### ISSUE THREAD

**Issue by dineshnadimpalli** [ashutosh1919/masterPortfolio#52]

**Comment by th3c0d3br34ker** [comment]
Suggested methods:
1. use of styled components
2. predefining icons and rendering if user has given the data.

**Comment by dineshnadimpalli** [comment]
Hi, @th3c0d3br34ker can you open another issue and raise a PR if you have any suggested solution for the 2nd point you mentioned. I believe that was not the scope of this issue.

**Comment by th3c0d3br34ker** [comment]
@dineshnadimpalli  your PR solves the problem 🐞 . 😄 I don't think it requires another PR.

**Comment by dineshnadimpalli** [comment]
> @dineshnadimpalli your PR solves the problem 🐞 . 😄 I don't think it requires another PR.

Cool @th3c0d3br34ker 😁

**Comment by th3c0d3br34ker** [comment]
why fix something which is not broken?

**Comment by dineshnadimpalli** [comment]
As suggested here https://github.com/ashutosh1919/masterPortfolio/pull/38#issuecomment-668558546 and the discussion that went through after that. Thought, it would be better to improve the code to reduce the inconsistency and raised this issue.

**Comment by th3c0d3br34ker** [comment]
I was talking about raising a new PR @dineshnadimpalli

**Comment by dineshnadimpalli** [comment]
Oops!😅 misunderstood. Yeah, regarding the PR, as the old one was already merged thought of adding a new one. Will continue on the same from next time. Thanks for the suggestion @th3c0d3br34ker 👍😄
