### ISSUE TITLE
Github Page issue

### ISSUE THREAD

**Issue by gopinath2018** [ashutosh1919/masterPortfolio#54]
https://github.com/gopinath2018/gopinath2018.github.io

I done everything a s mentioned in masterportfolio. At the end im interested to upload on github pages. i created a repo and uploaded. But not able to create a website. Anyone try to solve this issue.  

Where im making mistake?

**Comment by th3c0d3br34ker** [comment]
did you run `npm run build` ?

**Comment by gopinath2018** [comment]
Yes, It showing errors. can you try for my lot of errors

Creating an optimized production build...
Failed to compile.

.\src\index.js
Cannot find module: 'styletron-engine-atomic'. Make sure this package is installed.

You can install this package by running: npm install styletron-engine-atomic.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! masterPortfolio@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the masterPortfolio@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ELCOT\AppData\Roaming\npm-cache\_logs\2020-08-05T04_40_22_244Z-debug.log

**Comment by th3c0d3br34ker** [comment]
Delete the <-username->.github.io repository on Github, then run `npm run build`. Next upload all the contents of the `build` folder to <-username->.github.io.

**Comment by gopinath2018** [comment]
Yes, I tried. and uploaded on github. 

it showing 404 file not found @th3c0d3br34ker

**Comment by gopinath2018** [comment]
My website is deployed on the website. But only when i click view deployment it is working. when i type the website it is not working. 

www.gopinath2018.github.io is not working

when i click the view deployment button

it directs to 

www.gopinath2018.github,io/#/

how to remove this #? @th3c0d3br34ker

**Comment by th3c0d3br34ker** [comment]
1. There is no `www` in the address. 
2. The `#` will remain there as that is how it is.

You can simply give `gopinath2018.github.io` as you portfolio website address and it should work fine. 😄

**Comment by gopinath2018** [comment]
Not working 404 error is coming

**Comment by th3c0d3br34ker** [comment]
When I open [this](https://gopinath2018.github.io) I can see your portfolio site.

Please, describe your issue more, so that I can help you out.

**Comment by gopinath2018** [comment]
Yes, Thanks I again deployed. It's working
