### ISSUE TITLE
Need modification in experience cards.

### ISSUE THREAD

**Issue by ashutosh1919** [ashutosh1919/masterPortfolio#58]
I like below cards more than the existing design. It is @dineshnadimpalli's implementation. Good work. 

@dineshnadimpalli, can you raise PR to add this to masterPortfolio.

<img width="587" alt="Screenshot 2020-08-05 at 12 13 16 PM" src="https://user-images.githubusercontent.com/20843596/89380791-c35a9500-d715-11ea-9838-48d4253807ea.png">

**Comment by ashutosh1919** [comment]
@dineshnadimpalli, we need to change this thing that we need to make width 100% in this

**Comment by dineshnadimpalli** [comment]
Thanks @ashutosh1919 . Sure, will try something with 100% width and will also try adding the description part to this one.

**Comment by saiteja13427** [comment]
Now this task is open to anyone.

Please comment here if you want to take it up and I will assign it to you!

**Comment by saiteja13427** [comment]
Sure @Vyomrana02, assigning it to you.
Reach out in case of any queries!

**Comment by saiteja13427** [comment]
@Vyomrana02 Looks good.

How about adding skill icons as well and if skill icons are not there, then maybe that empty space shouldn't be there?

**Comment by saiteja13427** [comment]
This also looks fine to me, what do you think @ashutosh1919, Should we add a description or skills to the cards?

Also @Vyomrana02, in the latest image I can see the vertical lines behind the blue circles, that shouldn't happen.

**Comment by ashutosh1919** [comment]
@saiteja13427 @Vyomrana02 I think we should include description for the job role.

**Comment by saiteja13427** [comment]
Yeah, let us add description!

**Comment by ashutosh1919** [comment]
@Vyomrana02 have you raised a PR or are you still working in your fork? Coz I don't see PR here. Please attach it here if you have already raised.

**Comment by Vyomrana02** [comment]
Merged in #296 .
