### ISSUE TITLE
Need to add new social media

### ISSUE THREAD

**Issue by ashutosh1919** [ashutosh1919/masterPortfolio#64]
Now, we can add YouTube to the social media list. People who won't need that will remove that from list.

My Channel: https://www.youtube.com/channel/UC_amoXmmxSY9KusoDczDTXQ

**Comment by th3c0d3br34ker** [comment]
Do you need a PR? @ashutosh1919

**Comment by ashutosh1919** [comment]
Added by [this commit](https://github.com/ashutosh1919/masterPortfolio/commit/a334482c96abc0dd99b1b234cf315965d227ef36)
