### ISSUE TITLE
Adding Memories(Photo gallery) Section in Header 

### ISSUE THREAD

**Issue by Tanya-Goel** [ashutosh1919/masterPortfolio#67]
In this section,one would be able to include his/her most cherishable moments in the form of pictures or any winning moment photos that can be considered as a part of his/her achievement.

**Comment by th3c0d3br34ker** [comment]
It seems like a good addition to me. @ashutosh1919  @danielmarostica  thoughts?

**Comment by ashutosh1919** [comment]
@th3c0d3br34ker , yes @Tanya-Goel had discussion with me. Thanks for issue @Tanya-Goel . Also, she is working on PR.

**Comment by danielmarostica** [comment]
I particularly support this idea because I created something like this myself, however pretty makeshift: https://danielmarostica.github.io/#/photography

**Comment by saiteja13427** [comment]
I think a new memories page doesn't align with the goals of this project.

Thus closing this issue and the corresponding PR.

@Tanya-Goel if you still think we should add this, feel free to raise a new issue and we can discuss it further.
