### ISSUE TITLE
Splash Screen SVG Animation

### ISSUE THREAD

**Issue by pratikdaigavane** [ashutosh1919/masterPortfolio#7]
Hi,
How should I modify SVG Animation in the splash screen?

**Comment by ashutosh1919** [comment]
@pratikdaigavane , Thanks for the issue! Working on to build a tutorial for it since Splash SVG animation is not customizable.

**Comment by pratikdaigavane** [comment]
@ashutosh1919 Thanks!

**Comment by pratikdaigavane** [comment]
HI,
Is it okay if you can share your Figma project for the splash screen?

**Comment by ashutosh1919** [comment]
As of now, We have given option for not to have splash screen if you don't know how to design logo. You can do that just by assigning `false` to `isSplash` in `src/portfolio.js`. Closing this one as part of that.
