### ISSUE TITLE
Remove a component

### ISSUE THREAD

**Issue by advian123** [ashutosh1919/masterPortfolio#72]
I am pretty much new to open-source, so I don't want to include the section opensource. How can I remove it??

**Comment by advian123** [comment]
Sorry but it didn't work

**Comment by th3c0d3br34ker** [comment]
Remove the whole 
```js
 <li>
                <NavLink
                  to="/opensource"
                  tag={Link}
                  activeStyle={{ fontWeight: "bold" }}
                  style={{ color: theme.text }}
                  onMouseEnter={(event) => onMouseEnter(event, theme.highlight)}
                  onMouseOut={(event) => onMouseOut(event)}
                >
                  Open Source
                </NavLink>
</li>
```

**Comment by advian123** [comment]
Also tried that, but now it's only showing OpenSource in the header section, but I click it, there is no content in it. 
I just want to simply remove the opensource from the website.

**Comment by th3c0d3br34ker** [comment]
What i suggested will remove it completely.
Can you please push the code to GitHub and share the repository link here? So that's its easier to understand.

**Comment by rahulrachh** [comment]
The solution given by @th3c0d3br34ker worked for me. I removed the OpenSource and Contact section this way by removing that piece of code from header.js. See my code at [link](https://github.com/rahulrachh/my-github-portfolio/blob/d6d244800df8e73e6f6f11cbc8e47758664fef0a/src/components/header/Header.js#L86)

**Comment by rajesh1421** [comment]
The solution given by @th3c0d3br34ker also worked for me. I removed the **Experience,Projects and OpenSource section** this way by removing that piece of code from header.js.

**Comment by Soumya-9641** [comment]
Hey maintainer,I can solve this issue.Can you please assign this to me?

**Comment by ashutosh1919** [comment]
@Soumya-9641 please raise PR and we will assign this issue to you

**Comment by Soumya-9641** [comment]
@ashutosh1919  can you please tell me the specific task like which component need to be removed.So that I can do my task smoothly

**Comment by ashutosh1919** [comment]
@Soumya-9641 I don't think there is any requirement to do that. @th3c0d3br34ker has already explained it [here](https://github.com/ashutosh1919/masterPortfolio/issues/72#issuecomment-679829395)
