### ISSUE TITLE
In education component the logo of your college is wrong please take a look into it and update.

### ISSUE THREAD

**Issue by VNDhanush** [ashutosh1919/masterPortfolio#74]
@ashutosh1919

**Comment by ashutosh1919** [comment]
Please post screen shot. What do you mean by wrong?

**Comment by VNDhanush** [comment]
![Ashutosh](https://user-images.githubusercontent.com/43043075/92302318-eed8d580-ef88-11ea-8599-900250593ceb.JPG)
the college logo is in reverse

**Comment by VNDhanush** [comment]
And in home page in full stack development skills their is a spelling mistake [resposive]---->[responsive].Take a look into that too .

**Comment by ashutosh1919** [comment]
Feel free to contribute based on the browser you have. In mine, it's looking normal (not reversed)

**Comment by VNDhanush** [comment]
oh cool sorry regarding raising an issue then.

**Comment by ashutosh1919** [comment]
Opening it because there may be problems in some browsers and we need to resolve them. @VNDhanush , if you know the solution then feel free to raise the pull request.

**Comment by VNDhanush** [comment]
between I have cloned your repo and changed it as per my requirements. To deploy it in firebase I need to create firebase.js and then do the firebase commands that is it. Is that correct??

**Comment by ashutosh1919** [comment]
Firebase is not at all used in the project

**Comment by VNDhanush** [comment]
Yaa iknow but can i use it?

**Comment by dhruvkrishnavaid** [comment]
This issue is obsolete and can be safely closed.
It was already fixed [here](https://github.com/ashutosh1919/masterPortfolio/blob/848d92437a13d39f64649324e1015eb788bb2410/src/components/degreeCard/DegreeCard.js#L17).
