### ISSUE TITLE
Add Publication Component

### ISSUE THREAD

**Issue by saeidshirazi** [ashutosh1919/masterPortfolio#80]
hi   dear ashutosh,
tnx for great Project
cant you add Publication Component that I can Add my paper into it,
its really help me if you have time to do it because im not knowing react

**Comment by priyanshk20** [comment]
Can I take up this task? @ashutosh1919

**Comment by ashutosh1919** [comment]
@priyanshk20 , Yes you can take it up. Thanks for volunteering. Add the publication below github projects in Projects page. Don't add new page. That will be bad UX IMO.
