### ISSUE TITLE
Github token vulnerability in github_data_fetcher.js

### ISSUE THREAD

**Issue by Tasin5541** [ashutosh1919/masterPortfolio#81]
Current way of fetching github data using `github_data_fetcher.js` exposes the token. This can be fixed using `.env` file (Adding the actual token here and then calling it in `github_data_fetcher.js`) and adding it to `.gitignore`.

I have already done this. Can I contribute to this repo?

**Comment by Tasin5541** [comment]
I raised a PR flag

**Comment by ashutosh1919** [comment]
@Tasin5541 , till the PR is open. Let this issue stay open

**Comment by saiteja13427** [comment]
Closing this issue. The problem will be now handled in #220
