### ISSUE TITLE
Letters like 'g' 'j' 'p' are getting cropped in half in the project card

### ISSUE THREAD

**Issue by Tasin5541** [ashutosh1919/masterPortfolio#83]
![image](https://user-images.githubusercontent.com/42533823/93717732-8d745180-fb99-11ea-9536-03c0d33b3472.png)

**Comment by ashutosh1919** [comment]
@Tasin5541 , feel free to work on it. IMO, the fix would be to increase the line-height slightly. But above picture, I don't see anywhere the text is being cut like you mentioned. Can you please point it out?

**Comment by Tasin5541** [comment]
> @Tasin5541 , feel free to work on it. IMO, the fix would be to increase the line-height slightly. But above picture, I don't see anywhere the text is being cut like you mentioned. Can you please point it out?

The orange circled portions

![IMG_20200921_093217](https://user-images.githubusercontent.com/42533823/93731099-621b5200-fbed-11ea-8b41-a406b8883d09.png)

**Comment by ashutosh1919** [comment]
@Tasin5541 , yeah thanks for noticing and raising the issue. I think increasing the value of line-height would solve the issue.

**Comment by Tasin5541** [comment]
> @Tasin5541 , yeah thanks for noticing and raising the issue. I think increasing the value of line-height would solve the issue.

I'll try increasing the height and decreasing the margin by same amount, so that the gap doesn't increase
