### ISSUE TITLE
getting error while npm run deploy

### ISSUE THREAD

**Issue by dhananjayjakhadi** [ashutosh1919/masterPortfolio#87]
![image](https://user-images.githubusercontent.com/31828887/95752463-0bde8380-0c6e-11eb-86a0-e87320c1e7cd.png)

**Comment by ashutosh1919** [comment]
@dhananjayjakhadi , you are pushing to my repository and not your own. You need to change remote origin.
`git remote add origin <YOUR_GITHUB_REPO_LINK>`
and then build and deploy it again.

**Comment by dhananjayjakhadi** [comment]
![image](https://user-images.githubusercontent.com/31828887/95759361-98417400-0c77-11eb-8c4f-15e071b26e09.png)
 My remote origin already exists

**Comment by ashutosh1919** [comment]
`git remote rm origin` to remove the origin 
`git remote add origin <YOUR_GITHUB_REPO_LINK>`

**Comment by saiteja13427** [comment]
I assume that this problem is now solved.

Thus closing it!
